# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTickerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('open_quote', models.DecimalField(decimal_places=10, max_digits=19)),
                ('high_quote', models.DecimalField(decimal_places=10, max_digits=19)),
                ('low_quote', models.DecimalField(decimal_places=10, max_digits=19)),
                ('close_quote', models.DecimalField(decimal_places=10, max_digits=19)),
                ('volume_quote', models.DecimalField(decimal_places=10, max_digits=19)),
                ('quote_time', models.DateField(db_index=True)),
            ],
        ),
    ]
