# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_vantage_grabber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRocTickerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('roc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('quote_time', models.DateField(db_index=True)),
            ],
        ),
    ]
