# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_vantage_grabber', '0002_dailyroctickerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroctickerdata',
            name='time_period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
