# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_vantage_grabber', '0003_dailyroctickerdata_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroctickerdata',
            name='time_period',
            field=models.IntegerField(db_index=True),
        ),
    ]
