# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoloniexCoinPairData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pair', models.CharField(db_index=True, max_length=10)),
                ('last', models.DecimalField(decimal_places=10, max_digits=19)),
                ('lowest_ask', models.DecimalField(decimal_places=10, max_digits=19)),
                ('highest_bid', models.DecimalField(decimal_places=10, max_digits=19)),
                ('percent_change', models.DecimalField(decimal_places=10, max_digits=19)),
                ('base_volume', models.DecimalField(decimal_places=10, max_digits=19)),
                ('quote_volume', models.DecimalField(decimal_places=10, max_digits=19)),
                ('is_frozen', models.IntegerField()),
                ('high_24hr', models.DecimalField(decimal_places=10, max_digits=19)),
                ('low_24hr', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='PoloniexCoinPairDataCandles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pair', models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
