# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poloniex_grabber', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoloniexCoinPairData',
            new_name='PoloniexCoinPairDataRaw',
        ),
    ]
