# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poloniex_grabber', '0003_auto_20171119_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poloniexcoinpairdataraw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
